### ISSUE TITLE
Markdown editor not displaying errors

### ISSUE THREAD

**Issue by j-zhao** [music-markdown/music-markdown#131]
Upon saving, if errored, save button will animate but error blocks save. This is bad UX.

Example:

```
Uncaught TypeError: Cannot read property 'appendChild' of undefined
    at VM669 lstr.js:26
(anonymous) @ VM882 lstr.js:26
MarkdownEditor.js:82 Uncaught (in promise) DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at https://music-markdown.github.io/static/js/main.15b8c05f.chunk.js:1:11635
    at w (https://music-markdown.github.io/static/js/2.f4faffc7.chunk.js:1:748427)
    at Generator._invoke (https://music-markdown.github.io/static/js/2.f4faffc7.chunk.js:1:748215)
    at Generator.e.<computed> [as next] (https://music-markdown.github.io/static/js/2.f4faffc7.chunk.js:1:748606)
    at r (https://music-markdown.github.io/static/js/2.f4faffc7.chunk.js:1:9499)
    at s (https://music-markdown.github.io/static/js/2.f4faffc7.chunk.js:1:9701)
    at https://music-markdown.github.io/static/js/2.f4faffc7.chunk.js:1:9760
    at new Promise (<anonymous>)
    at https://music-markdown.github.io/static/js/2.f4faffc7.chunk.js:1:9642
    at Object.<anonymous> (https://music-markdown.github.io/static/js/2.f4faffc7.chunk.js:1:822821)
```

**Comment by shadanan** [comment]
This is fixed now by using a btoa function that is unicode aware.
